version: '3.8'

services:
  simulator:
    container_name: simulator
    networks:
      - bridge_network
      - simulator_network
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_ROOT_PASS
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 7777:7777
    command: npm run start

networks:
  bridge_network:
      name: bridge_network
  simulator_network:
      name: simulator_network