version: '3.8'

services:
  simulator:
    container_name: simulator
    networks:
      - simulator_network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
    ports:
      - 7777:7777
    command: npm run start

networks:
  public:
    external:
      name: public