version: '3.8'

services:
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
    networks:
      - mongodb_network
    container_name: simulator
    expose:
      - 7777
    ports:
      - 7777:7777
    command: npm run start